version: '3.4'

networks:
  unleashed-network:
    name: unleashed-network
    #external: true

services:
  unleashdemo.api:
    image: ${DOCKER_REGISTRY-}unleashdemoapi
    build:
      context: .
      dockerfile: UnleashDemo.API/Dockerfile
    networks:
     - unleashed-network

  unleashed-server:
    image: unleashorg/unleash-server
    container_name: unleashed-server
    hostname: unleashed-server
    environment:
        DATABASE_HOST: "postgres"
        DATABASE_NAME: "unleash"
        DATABASE_USERNAME: "unleash_user"
        DATABASE_PASSWORD: "unleashed"
        DATABASE_SSL: "false"
    ports:
     - "4242:4242"
    networks:
     - unleashed-network
    depends_on:
     - postgres_db
    restart: always


  #Postgre Database
  postgres_db:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: "unleash"
       POSTGRES_USER: "unleash_user"
       POSTGRES_PASSWORD: "unleashed"
    ports:
      - "5432:5432"
    networks:
      - unleashed-network
  #Adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - unleashed-network